version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'IntexSoft'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=IntexSoftProject'